# **`ravel()` vs flatten()**



`ravel()` is used to **convert a multi-dimensional array into a 1D array (flatten it)**.

### ✅ Basic Syntax

```python
numpy.ravel(array)
```

In [2]:
import numpy as np

In [3]:
### ✅ Example 1: Simple Flatten

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.ravel()

print(flat)

#```[1 2 3 4 5 6]

[1 2 3 4 5 6]



### ✅ Key Point (VERY IMPORTANT 🔥)

👉 `ravel()` **returns a view (not a copy)** whenever possible.

That means:

* Changing the flattened array **can affect the original array**

In [4]:
### ✅ Example 2: View Behavior

arr = np.array([[1, 2], [3, 4]])

flat = arr.ravel()
flat[0] = 100

print("Flat:", flat)
print("Original:", arr)

#**Output:**
#```
#Flat: [100   2   3   4]
#Original: [[100   2]
#           [  3   4]]
#```

#👉 Original array changed — because it's a **view**

Flat: [100   2   3   4]
Original: [[100   2]
 [  3   4]]


### 🔁 Difference: `ravel()` vs `flatten()`

| Feature        | ravel()       | flatten()       |
| -------------- | ------------- | --------------- |
| Return type    | View (mostly) | Always Copy     |
| Memory usage   | Efficient     | More memory     |
| Speed          | Faster        | Slightly slower |
| Safe to modify | ❌ No          | ✅ Yes           |


In [6]:
### ✅ Example 3: flatten()

flat2 = arr.flatten()
flat2[0] = 999

print(arr)   # original unchanged
print(flat2)  

[[100   2]
 [  3   4]]
[999   2   3   4]


### 🎯 Interview Tip

👉 Use `ravel()` when:

* You want **better performance**
* You don’t need to protect original data

👉 Use `flatten()` when:

* You want **safe copy**


### 🔥 One-line Summary

> `ravel()` = **fast flattening (view-based)**

# **2D: Indexing in 2D Arrays**

In [7]:
#Great question 👌 — this is **core NumPy indexing**, very important for interviews 🔥
#Let’s break each one **step by step with intuition + output**.

## 🔢 Given Array

```python
import numpy as np

mat = np.array([
   [1,2,3],
   [4,5,6],
   [7,8,9]
])
```

👉 Matrix looks like:

```
Row\Col   0   1   2
        -------------
0       1   2   3
1       4   5   6
2       7   8   9
```

## 🔹 1. `mat[0][1]`

```python
mat[0][1]
```

### 👉 Step-by-step:

* `mat[0]` → first row → `[1,2,3]`
* `[1]` → second element of that row → `2`

✅ **Output:**

```
2
```

## 🔹 2. `mat[0,1]`

```python
mat[0,1]
```

👉 Direct indexing using **row, column**

* Row = 0
* Column = 1

✅ **Output:**

```
2
```

### 🔥 Important:

* `mat[0][1]` → two steps
* `mat[0,1]` → single step (faster, preferred)

## 🔹 3. `mat[:,2]`

```python
mat[:,2]
```

👉 Meaning:

* `:` → all rows
* `2` → column index 2

👉 Take **3rd column from all rows**

✅ **Output:**

```
[3 6 9]
```

## 🔹 4. `mat[0:2,1:]`

```python
mat[0:2,1:]
```

👉 Break it:

### Rows: `0:2`

* row 0 and row 1
* (2 is excluded)

### Columns: `1:`

* column 1 onward → `[2,3]`, `[5,6]`

✅ **Output:**

```
[[2 3]
 [5 6]]
```

## 🔹 5. `mat[::-1, ::-1]`

```python
mat[::-1, ::-1]
```

👉 This is **reverse slicing**

### `[::-1]` → reverse rows

### `[::-1]` → reverse columns

👉 Full matrix reversed (both axes)

✅ **Output:**

```
[[9 8 7]
 [6 5 4]
 [3 2 1]]
```

## 🔥 Summary Table

| Expression       | Meaning                 | Output          |
| ---------------- | ----------------------- | --------------- |
| `mat[0][1]`      | Row 0 → index 1         | `2`             |
| `mat[0,1]`       | Row 0, Column 1         | `2`             |
| `mat[:,2]`       | All rows, column 2      | `[3 6 9]`       |
| `mat[0:2,1:]`    | Rows 0–1, columns 1–end | `[[2 3],[5 6]]` |
| `mat[::-1,::-1]` | Reverse rows & columns  | Full reverse    |

## 🎯 Interview Tip

👉 Always prefer:

```python
mat[row, col]
```

instead of:

```python
mat[row][col]
```

Because:

* Faster
* Cleaner
* Works better in multi-dimensional arrays

# **Matrix Multiplication**

Great — this is a **very important concept (NumPy + linear algebra + interviews)** 🔥

---

## 🔷 Matrix Multiplication (Concept + Rule)

## ✅ Rule (Most Important ⚠️)

👉 You can multiply two matrices **only if**:

> **Columns of first matrix = Rows of second matrix**

### 📌 Shape Rule:

```
(A m×n)  ×  (B n×p)  → Result = (m×p)
```

---

## 🔢 Example

## Matrix A (2×3)

```
A = [
 [1, 2, 3],
 [4, 5, 6]
]
```

## Matrix B (3×2)

```
B = [
 [7, 8],
 [9, 10],
 [11,12]
]
```

👉 Valid because:

* A → 3 columns
* B → 3 rows ✅

---

## 🔄 How Multiplication Works

👉 Each element = **dot product of row × column**

---

## 🔹 Step-by-step Calculation

### First row × First column:

```
(1×7) + (2×9) + (3×11)
= 7 + 18 + 33 = 58
```

### First row × Second column:

```
(1×8) + (2×10) + (3×12)
= 8 + 20 + 36 = 64
```

---

### Second row × First column:

```
(4×7) + (5×9) + (6×11)
= 28 + 45 + 66 = 139
```

### Second row × Second column:

```
(4×8) + (5×10) + (6×12)
= 32 + 50 + 72 = 154
```

---

## ✅ Final Result (2×2 Matrix)

```
[
 [58,  64],
 [139, 154]
]
```

---

## 🐍 NumPy Implementation

```python
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8],
              [9,10],
              [11,12]])

result = np.dot(A, B)
# OR
result = A @ B

print(result)
```

### ✅ Output:

```
[[ 58  64]
 [139 154]]
```

---

## 🔥 Important Notes (Interview)

### ❌ This is NOT matrix multiplication:

```python
A * B   # element-wise multiplication
```

### ✅ Correct ways:

```python
np.dot(A, B)
A @ B
np.matmul(A, B)
```

---

## ⚡ Quick Visualization Trick

👉 Think like this:

* Row from A → →
* Column from B ↓

Multiply + Add = one cell

---

## 🎯 One-line Summary

> Matrix multiplication = **Row × Column (dot product)**

---

If you want next:
👉 I can give:

* tricky interview questions
* broadcasting vs matrix multiplication
* real ML use case (very important)

Just say 👍
